---
title: "Transparency of COVID-19-related research in medical journals"

author:
  - Ahmad Sofi-Mahmudi^[Seqiz Health Network, Kurdistan University of Medical Sciences, Seqiz, Iran.; a.sofimahmudi@gmail.com] ^[Cochrane Iran Associate Centre, National Institute for Medical Research Development (NIMAD), Tehran, Iran.]
  - Eero Raittio*^[Institute of Dentistry, University of Eastern Finland, Kuopio, Finland.; eero.raittio@uef.fi]
  - Sergio E. Uribe^[Department of Conservative Dentistry and Oral Health & Bioinformatics Research Unit, Riga Stradins University, Riga, Latvia.; sergio.uribe@rsu.lv] ^[School of Dentistry, Universidad Austral de Chile, Valdivia, Chile]
  
format: html
#format:
#  pdf:
#    colorlinks: true
editor: visual
bibliography: references.bib
csl: vancouver.csl
---

**Corresponding author:** Eero Raittio; **Address**: University of Eastern Finland, Institute of Dentistry, P.O. Box 1627, FI-70211 Kuopio, Finland; **Telephone**: +358 294 45 1111; **Email**: [eero.raittio\@uef.fi](mailto:eero.raittio@uef.fi).

**Authors' contributions:** All authors conceived and designed, and wrote and revised the protocol.

# Abstract

**Objective:** The recent pandemic has shown how crucial it is to have access to quality medical information and data that allows people to have confidence in healthcare decisions. We aimed to assess the use of transparency indicators (data availability, code availability, statements of protocol registration and conflicts of interest and funding disclosures) from open access Coronavirus disease 2019 (COVID-19) related articles.

**Methods:** We searched and exported all open-access COVID-19-related articles from PubMed-indexed journals available in the Europe PMC database published between January 2020 and December 2021. We detected transparency indicators with a validated and automated tool developed to extract the indicators from the downloaded articles. Basic journal- and article-related information were retrieved from the PMC database. We used R for the searches (europepmc package), data handling, analysis (rtransparent package) and reporting (ggplot2 package).

**Results:** Of 72,999 available articles published in XX medical journals, 87.0%, (95% CI: 86.8%--87.2%) provided conflicts of interest disclosure and 68.9% (95% CI: 68.7%--69.2%) funding disclosure and 3.6%, (95% CI: 3.5%--3.7%) were preregistered. 8.7% (95% CI: 8.6%--8.9%) of studies shared raw data and 3.1% (95% CI: 3.0%--3.2%) of studies shared code. Transparent practices were more common in articles published in 2021 than in 2020.

**Conclusion:** While the majority of the papers had a COI disclosure, the prevalence of the other transparency practices was far from the acceptable level. Even surprisingly low, particularly in terms of data sharing, taking into account global initiatives to improve open science in COVID-19 related research. A much stronger commitment to open science practices, particularly to preregistration, data and code sharing, is needed from all stakeholders.

***Keywords:*** COVID-19; Data; FAIR data principles; Open Science.

# Introduction

COVID-19 pandemic launched an incredibly fast and voluminous avalanche of scientific publications across the different fields of science. There has been discussion and many examples related to poor or suboptimal data, methods and other scientific practices in COVID-19-related studies [@Glasziou2020; @besançon2021; @luengo-oroz2020; @schwab2020\]. However, in addition to fast and successful development of safe and effective vaccination, it is possible that transparent scientific practices, like data and code sharing, have helped to fight pandemic globally \[@besançon2021; @vuong2022\]. That being said, comprehensive picture of transparency practices in COVID-19-related medical literature is still lacking. As an example, it is unknown whether open science initiatives related to COVID-19 pandemic \[@besançon2021; @vuong2022], for instance to advance data sharing, has led to higher number of articles sharing data in COVID-19 research compared to what has been seen in studies in general in biomedical literature [@serghiou2021].

Our aim was to assess the adherence to transparent scientific practices (data sharing, code sharing, conflict of interest, COI, disclosures, funding disclosures, and protocol registration) from open access full-text COVID-19-related articles published in PubMed indexed journals from the Europe PubMed Central (EPMC) database. We mapped adherence to transparency practices across time, journal impact factor (JIF) and citations articles have received

# Methods

The protocol of this study was published beforehand on the Open Science Framework (OSF) website ([osf.io/5kx2n](https://osf.io/5kx2n)). All code and data related to the study were shared via its OSF repository ([osf.io/x3kb6](https://osf.io/x3kb6/)) at the time of submission of the manuscript.

## Data sources and study selection

We searched for open access COVID-19-related PubMed-indexed articles available in the EPMC database. We restricted our search to papers in English and considered papers published from 2020-01-01 to 2021-12-31 with variants of COVID-19 keyword in their title, keywords, or results. This enabled us to bypass screening for COVID-19-related papers and decrease the human labor for our research. We confirmed our approach by choosing a random sample of 100 papers and of those, all were relevant to COVID-19.

The search query was as follows:

(COVID-19 query for title, keywords, and results) AND (SRC:"MED") AND (LANG:"eng" OR LANG:"en" OR LANG:"us") AND (FIRST_PDATE:\[2020-01-01 TO 2021-12-31\]) AND (OPEN_ACCESS:y) AND (PUB_TYPE:"Journal Article" OR PUB_TYPE:"research-article" OR PUB_TYPE:"rapid-communication" OR PUB_TYPE:"product-review")'

The full COVID-19 query is available in Appendix 1.

We downloaded all identified available records in XML full-text format (for full-text evaluation) using the metareadr package [@metareadr] from the database.

## Data extraction and synthesis

We assessed adherence to five transparency practices in the articles:

-   data availability,

-   code availability,

-   COI disclosures,

-   funding disclosures,

-   protocol registration.

To do so, we used a validated and automated tool developed by Serghiou et al. [@serghiou2021] suitable to identify these five transparent practices from articles in XML format from the EPMC database.

Basic journal- and article-related information (publisher, publication year, citations to article and journal name) were retrieved from the EPMC database. We downloaded additional information about journal impact factors from the Journal Citation Reports (ٰ[jcr.clarivate.com](https://jcr.clarivate.com/)).

We also calculated the proportion of articles available as open-access full-texts via the Europe PMC from the total number of COVID-19-related articles in the database.

## Data analysis

We used R v4.1.2 [@R-base] for searches, data handling, analysis and reporting. The searches and data export from the Europe PMC were conducted with the europepmc package [@europepmc]. Transparency indicators from the available full-texts were extracted with the rtransparent package [@rtransparent]. Trends over time in transparency indicators by journal- and article-related information were reported using descriptive tabulations and graphical illustrations, for instance using the ggplot2 package [@ggplot2]. We used the numbers for sensitivity and specificity of the rtransparent package (3) to generate 95% confidence intervals (CIs) for our prevalence estimates of the transparency indicators with the epiR package [@epiR]. We also provided monthly trends for transparency indicators, to check whether there were any trends in transparency practices over time. We used Chi-square for comparing indicators between years and the Wilcoxon rank sum test to test whether there was a relationship of transparency indicators with citations to articles and JIFs. The thorough system information for the analysis is available in Appendix 2.

# Results

The total number of COVID-19-related papers (open access and non-open access) was 175550, of which full texts of 133470 papers (76.0%) were accessible as open-access via the EPMC. However, 852 (0.6%) were not downloadable because of technical issues and thus were excluded from our analyses. Of those 132618 remaining articles, 47550 were published in 2020, 75857 in 2021, and 9211 in the first two months of 2022 (Appendix 3).

These articles were published in 6084 journals of which the top five were International Journal of Environmental Research and Public Health (n=3711), PLoS ONE (n=3059), Scientific Reports (n=1717), Frontiers in Public Health (n=1351), and Frontiers in Psychology (n=1341). The mean and the median of the number of citations to these articles were 12.0 (standard deviation (SD) = 92.27) and 2 (interquartile range (IQR) = 7). The highest cited article with 15549 citations was an article published in the Lancet in 2020 [@huang2020].

About nine-tenth of the articles (n=115405) had a statement to disclose COI (87.0%, 95% CI: 86.8%--87.2%). Articles published in 2022 had a higher rate of COI disclosure (91.4% vs 89.1% for 2021, and 82.9% for 2020, P \< 0.001). More than two-thirds of the references had a funding statement (n=91425) (68.9%, 95% CI: 68.7%--69.2%). Articles in 2022 had a funding statement more frequently than two other years (79.0% vs 73.1% for 2021, and 60.4% for 2020, P \< 0.001). Less than 1 in 25 of the articles (n=4708) were registered beforehand (3.6%, 95% CI: 3.5%--3.7%) and the rate was higher in 2022 (5.4% vs 4.2% for 2021, and 2.2% for 2020, P \< 0.001).

Regarding data and code availability, less than 1 in 11 articles had shared their data (n=11552) (8.7%, 95% CI: 8.6%--8.9%). Articles in 2022 had shared data more frequently (11.9% vs 9.6% for 2021, and 6.7% for 2020, P \< 0.001). Less than 1 in 30 of the articles (n=4055) had shared their code (3.1%, 95% CI: 3.0%--3.2%) and the rate was higher in 2022 (4.0% vs 3.5% for 2021, and 2.2 for 2020, P \< 0.001).

A total of 38383 articles were published in journals with a Journal Impact Factor (JIF). Papers that had a COI disclosure, funding statement and were registered tend to be published in journals with lower JIF (P = 0.003, \< 0.001, and = 0.007, respectively). Detailed information is illustrated in Table 1.

Table 1. Citations and journal impact factor by transparency indicators.

|                    | Citations to article |         |          | Journal Impact Factor |            |          |
|--------------------|----------------------|---------|----------|:----------------------|:-----------|----------|
| Measurement        | Median (IQR)         |         | P-Value  | Median (IQR)          |            | P-value  |
|                    | With                 | Without |          | With                  | Without    |          |
| COI disclosure     | 2 (6)                | 2 (7)   | \< 0.001 | 4.1 (2.31)            | 7.2 (5.12) | \< 0.001 |
| Funding disclosure | 2 (6)                | 2 (8)   | \< 0.001 | 4.1 (2.32)            | 4.1 (2.94) | \< 0.001 |
| Registration       | 1 (5)                | 2 (6)   | \< 0.001 | 3.8 (2.38)            | 4.2 (2.44) | \< 0.001 |
| Data sharing       | 2 (8)                | 2 (6)   | \< 0.001 | 4.0 (2.98)            | 4.1 (2.36) | \< 0.001 |
| Code sharing       | 2 (8)                | 2 (6)   | 0.70     | 4.4 (4.41)            | 4.1 (2.32) | 0.08     |

: P-value based on the Wilcoxon rank sum test.\
COI: Conflict of interest; SD: Standard deviation; IQR: Inter-quartile range.

Over half of the papers had two transparency indicators (n=74085, 55.9%). Less than 0.1% (n=45) had all five indicators while 9.0% (n=11890) had no indicators. Among papers with two transparency indicators, the majority had COI and funding disclosures (99.3% and 97.9%, respectively).

Figure 1 shows the monthly trend for three transparency indicators. According to the figure, all indicators showed increasing monthly trend. However, the increasing trends for COI and funding disclosures were steeper compared to three other indicators.

# Discussion

Adherence to transparency practices increased over time in COVID-19 related medical literature during 2020-2021. Adherence to reporting COI disclosure was high throughout study period, in addition most of articles had funding disclosure. Data sharing, code sharing and protocol registration were rare, but improved little over study period. COI disclosures seemed to be more common in articles published in lower impact journals, otherwise differences in transparency practices according to received citations and JIF were small.

Adherence to transparency practices was at similar level in COVID-19 related literature than in other biomedical literature analyzed with the same methods (see Fig 3 in \[@serghiou2021\]). This is surprising particularly when considering worldwide, remarkable and noble initiatives related to enhancing open science to tackle the pandemic. As early as in January 2020, over 100 organizations, including journals, publishers, funders, universities and other institutions, signed a statement that aimed to ensure free access to research data, tools and other information related to COVID-19 \[@vuong2022; @coronavi\]. Later also other initiatives to support the goal emerged, for instance COVID-19 Open Research Dataset (CORD-19)[@cord-19], a free resource of over 280,000 articles about the COVID-19 virus. However, it is possible that the algorithms used here did not efficiently detect all different ways of sharing data and material emerged after the pandemic, because the algorithms were validated before the pandemic [@serghiou2021].

In comparison to other studies on the transparency of COVID-19 related research is difficult due to different methodologies and scale of our research. However, it seems that data sharing was little less common than in our sample than what was the proportion detected in the beginning of the pandemic measured by the investigation of associated data in PubMed Central \[@lucas-dominguez2021\]. In addition, the proportion of studies which shared data in our study sample was lower than in COVID-19 related preprints shared via medRxiv and bioRxiv \[@strcic2022\]. Lacking preregisteration, sharing code and COI have got attention during the pandemic \[@Glasziou2020; @besançon2021; @luengo-oroz2020\], however we are not aware of the investigation of transparency practices in these aspects in COVID-19 related research in this scale in medical research.

Despite we used representative data and validated methods to investigate transparency practices in COVID-19-related research, our study has some weaknesses. The study sample was restricted to open access articles in the EPMC database which may not correspond to all COVID-19-related studies published in medical journals. At least in general, the differences in transparency practices between open access and non-open access articles from Europe PMC are rather similar [@wallach2018a]. However, as the majority of COVID-19-related papers were available via EPMC (76%), this does not diminish the strength of our interpretations considerably.

Transparency is crucial to ensure the credibility of science and enable its assessment. Transparent scientific practices, like the ones we investigated here, have helped to fight pandemic globally [@besançon2021; @vuong2022]. However, your findings showed suboptimal adherence to data and code sharing and pre-registeration in COVID-19 related research, whilst majority of researchers had adhered to disclose funding and COI related to their COVID-19 related research. Stronger commitment to open science practices, particularly to preregistration, data and code sharing, is needed from all stakeholders.

# Acknowledgements

The computational analyzes were performed on servers provided by UEF Bioinformatics Center, University of Eastern Finland, Finland. The study was supported by a personal grant to ER from the Finnish Dental Society Apollonia.

# References
